on: workflow_dispatch

#name: ARM build
name: msvc rust

jobs:
  windows:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: 
          cargo build --release

      - uses: actions/upload-artifact@v2
        with:
          name: trojan-r.exe
          path: target/release/trojan-r.exe
          

  android:
    name: android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-linux-android
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-linux-android
      - uses: actions/upload-artifact@v2
        with:
           name: android-trojan-r
           path: target/aarch64-linux-android/release/trojan-r

  mipsel:
    name: mipsel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout trojan-r
        uses: actions/checkout@v2
        
#      - name: Checkout ring
#        uses: actions/checkout@v2
#        with:
#          repository: 'briansmith/ring'
#          path: './ring'

      - name: Checkout ring PR 1181 with mips support
        run: |
          git clone https://github.com/briansmith/ring.git
          cd ring
          git checkout 9cc0d45f4d8521f467bb3a621e74b1535e118188
          git fetch origin pull/1181/head:mips
          git config --global user.email "example.com"
          git config --global user.name "zrah"
          git merge mips --no-commit --no-ff --allow-unrelated-histories 
      
      - name: Patch Cargo.toml
        run: |
          echo '[patch.crates-io]' >> Cargo.toml
          echo 'ring = { path = "./ring" }' >> Cargo.toml

      #- uses: P3TERX/ssh2actions@v1.0.0
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: mipsel-unknown-linux-musl
          override: true
    
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target mipsel-unknown-linux-musl

      - uses: actions/upload-artifact@v2
        with:
           name: mips-trojan-r
           path: target/mipsel-unknown-linux-musl/release/trojan-r
  
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v2
        with:
           name: linux-trojan-r
           path: target/release/trojan-r
