on:
  workflow_dispatch

name: nightly

jobs:
  build-linux:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, armv7-unknown-linux-musleabihf, arm-unknown-linux-musleabihf, aarch64-unknown-linux-musl]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/trojan-r
      - name: Create Release Tag
        if: github.event_name == 'workflow_dispatch'
        id: create_release_tag
        uses: actions/create-release-tag@v1
        with:
          tag: ${{ github.run_number }}
          ref: ${{ github.ref }}
          message: Automatic Release Tag created by GitHub Actions
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
