on:
  workflow_dispatch

name: nightly

jobs:
  build-linux:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, armv7-unknown-linux-musleabihf, arm-unknown-linux-musleabihf, aarch64-unknown-linux-musl]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
  release:
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        with: 
          tag_name: v$VERSION   # 版本号,从环境变量获取
          release_name: Release v$VERSION 
          body_path: release_note.md
      - run: upload_artifacts.sh 
